name: Humanoid Path Planner
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-sitemap

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/hpp-doc"

github-url: "https://github.com/humanoid-path-planner/hpp-doc"
